// 01_reflex_game/angular/src/app/game/game.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-game',
  imports: [],
  templateUrl: './game.html',
})
export class Game implements OnInit {
  @Output() resultReady = new EventEmitter<number>();
  message = 'Click when the screen turns green!';
  reactionTime = 0;
  delay: number | null = null;
  interval: number | undefined = undefined;
  click = false;

  ngOnInit(): void {
    this.delay = Math.floor(Math.random() * 5000) + 2000; // Random delay between 2 and 6 seconds
    setTimeout(() => {
      this.message = 'Click now!';
      this.click = true;
      this.interval = setInterval(() => {
        this.reactionTime += 10;
      }, 10);
    }, this.delay);
  }

  getReactionTime() {
    clearInterval(this.interval);
    this.interval = undefined;
    this.resultReady.emit(this.reactionTime);
  }
}

// 01_reflex_game/react/src/components/Game.jsx
import { useEffect, useRef, useState } from "react";

function Game({ handleGameEnd }) {
  const [click, setClick] = useState(false);
  const [reactionTime, setReactionTime] = useState(0);

  const [message, setMessage] = useState("Click when the screen turns green!");

  const intervalRef = useRef(null);
  const timeoutRef = useRef(null);

  function handleClick() {
    if (intervalRef.current) {
      clearInterval(intervalRef.current);
    }
    handleGameEnd(
      reactionTime > 0
        ? `Your reaction time is: ${reactionTime} ms`
        : "Wait for the green box to appear!"
    );
  }

  useEffect(() => {
    const delay = Math.floor(Math.random() * 5000) + 1000;
    timeoutRef.current = setTimeout(() => {
      setMessage("Click now!");
      setClick(true);
      intervalRef.current = setInterval(() => {
        setReactionTime((prev) => prev + 10);
      }, 10);
    }, delay);

    return () => {
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
        timeoutRef.current = null;
      }
      if (intervalRef.current) {
        clearInterval(intervalRef.current);
        intervalRef.current = null;
      }

      setClick(false);
      setReactionTime(0);
      setMessage("Click when the screen turns green!");
    };
  }, []);

  return (
    <div className={`game ${click ? "click" : ""}`} onClick={handleClick}>
      <h2>{message}</h2>
    </div>
  );
}

export default Game;
